apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-alpha-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "eks-alpha/app-secret"
        objectType: "secretsmanager"
        objectAlias: "app-secret"
  secretObjects:
    - secretName: eks-alpha-app-secret
      type: Opaque
      data:
        - objectName: app-secret
          key: APP_SECRET