apiVersion: v1
kind: Service
metadata:
  name: eks-alpha-app
  namespace: default
  labels:
    app: eks-alpha-app
spec:
  selector:
    app: eks-alpha-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP