name: CD - Deploy to EKS

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER: eks-alpha-cluster
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/service-account.yaml
          kubectl apply -f k8s/secret-provider-class.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml

      - name: Update deployment image
        run: |
          kubectl set image deployment/eks-alpha-app \
            app=${{ steps.login-ecr.outputs.registry }}/eks-alpha-app:${{ github.event.workflow_run.head_sha }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/eks-alpha-app --timeout=120s

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get ingress
